language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} > "5" ]]; then pecl install uopz; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} > "5" ]]; then echo "extension=uopz.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer self-update

install: travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run
  - vendor/bin/phpunit --verbose
